function h = changeMarkerNames(h)

btkSetPointLabel(h, 'LatKnee', 'LATKN')
btkSetPointLabel(h, 'Sacrum', 'SAC')
btkSetPointLabel(h, 'Th1', 'TH1')
btkSetPointLabel(h, 'Th2', 'TH2')
btkSetPointLabel(h, 'Th3', 'TH3')
btkSetPointLabel(h, 'Th4', 'TH4')
btkSetPointLabel(h, 'Sh1', 'SH1')
btkSetPointLabel(h, 'Sh2', 'SH2')
btkSetPointLabel(h, 'Sh3', 'SH3')
btkSetPointLabel(h, 'Sh4', 'SH4')
btkSetPointLabel(h, 'MedAnk', 'MEDAN')
btkSetPointLabel(h, 'LatAnk', 'LATAN')
btkSetPointLabel(h, 'PostCalc', 'POSTC')
btkSetPointLabel(h, 'MedTub', 'MEDTU')
btkSetPointLabel(h, 'PeronT', 'PERON')
btkSetPointLabel(h, 'Navicular', 'NAVIC')
btkSetPointLabel(h, 'Met5Base', 'MET5B')
btkSetPointLabel(h, 'Met5Head', 'MET5H')
btkSetPointLabel(h, 'Met1Base', 'MET1B')
btkSetPointLabel(h, 'Met1Head', 'MET1H')
btkSetPointLabel(h, 'Toe1', 'TOE1')
btkSetPointLabel(h, 'Toe2', 'TOE2')
btkSetPointLabel(h, 'Toe5', 'TOE5')